/* @flow */
export const SEARCH_USER_NAME = "SEARCH_USER_NAME";
export const SET_TOGGLE_SEARCH_BUTTON_STATUS =
  "SET_TOGGLE_SEARCH_BUTTON_STATUS";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const SET_USERNAME = "SET_USERNAME";
export const SET_USER_PHOTO = "SET_USER_PHOTO";
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";
export const FETCHED_POSTS = "FETCHED_POSTS";
export const FETCH_DAY_OF_WEEK = "FETCH_DAY_OF_WEEK";
export const GET_DAY_OF_WEEK = "GET_DAY_OF_WEEK";
export const GET_DAY_OF_WEEK_SUCCESS = "GET_DAY_OF_WEEK_SUCCESS";
export const GET_DAY_OF_WEEK_FAILURE = "GET_DAY_OF_WEEK_FAILURE";
